FROM python:3.9-slim-bullseye

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

RUN pip install cryptography

CMD ["python", "app.py"]